### ISSUE TITLE
Вывесите в релизах собранную PDF’ку

### ISSUE THREAD

**Issue by Mazdaywik** [gogabr/pfds#33]
Создайте, пожалуйста, тег и вывесите под этим тегом в https://github.com/gogabr/pfds/releases собранную PDF’ку, чтобы читателям не приходилось самим клонировать репозиторий и собирать TeX’ом книгу.

Я сам уже давно собрал и прочитал Ваш перевод, и даже другим рекомендую. Но приходится при рекомендациях предупреждать, что по ссылке исходники в TeX.

Если это перевод не финальный, можно так и написать, что, дескать, это промежуточная версия, бета, требует вычитки…

**Comment by gogabr** [comment]
Сделал ровно так, как Вы предложили.
Спасибо!

**Comment by Mazdaywik** [comment]
Большое спасибо!

Не знал, что перевод бумажной книги Ваш, думал, что это независимый перевод. Теперь обязательно куплю бумажную книгу!

Ещё раз большое спасибо за Ваш труд!

**Comment by Mazdaywik** [comment]
Заказал бумажную книгу.
